/* KORbuild Finances — Edit Account V1 */
(() => {
'use strict';
const $=id=>document.getElementById(id); const db=()=>KORbuildAuth.client.schema('finances'); let workspace=null, accountId=null;
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
function msg(text,kind='error'){const e=$('form-message');e.textContent=text;e.className='message '+kind;}
function header(user){const n=workspace?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'André';$('user-name').textContent=n;$('user-email').textContent=user.email||'';$('user-avatar').textContent=initials(n);$('menu-full-name').textContent=n;$('menu-full-email').textContent=user.email||'';$('menu-avatar').textContent=initials(n);$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};}
async function init(){accountId=new URLSearchParams(location.search).get('id');if(!accountId){location.replace('accounts.html');return}const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const {data:ws,error:we}=await db().from('user_workspaces').select('id,display_name,setup_completed').eq('user_id',s.user.id).maybeSingle();if(we)throw we;if(!ws||!ws.setup_completed){location.replace('workspace.html');return}workspace=ws;header(s.user);const {data,error}=await db().from('accounts').select('id,name,account_type,currency,opening_balance').eq('id',accountId).eq('workspace_id',workspace.id).maybeSingle();if(error)throw error;if(!data){location.replace('accounts.html');return}$('account-name').value=data.name||'';$('account-type').value=data.account_type||'corrente';$('account-currency').value=data.currency||'BRL — Real brasileiro';$('opening-balance').value=data.opening_balance??'';}
$('account-form').onsubmit=async e=>{e.preventDefault();const button=$('save-account');button.disabled=true;msg('Salvando…','');try{const name=$('account-name').value.trim(),account_type=$('account-type').value,currency=$('account-currency').value,opening_balance=Number($('opening-balance').value);if(!name)throw Error('Informe o nome da conta.');if(!Number.isFinite(opening_balance)||opening_balance<0)throw Error('Informe um saldo inicial válido.');const {data,error}=await db().from('accounts').update({name,account_type,currency,opening_balance}).eq('id',accountId).eq('workspace_id',workspace.id).select('id').maybeSingle();if(error)throw error;if(!data)throw Error('Conta não encontrada ou sem permissão para alteração.');location.replace('accounts.html?updated=1');}catch(e){console.error(e);msg(e.message||'Não foi possível salvar as alterações.');button.disabled=false;}};
init().catch(e=>{console.error(e);msg('Não foi possível carregar a conta.');});
})();