/* KORbuild Finances — Accounts V1 */
(() => {
'use strict';
const $=id=>document.getElementById(id); const db=()=>KORbuildAuth.client.schema('finances'); let workspace=null, editingId=null;
const brl=(v,c='BRL')=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:(c||'BRL').split(' ')[0],maximumFractionDigits:2});
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
function header(user){const n=workspace?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'André';$('user-name').textContent=n;$('user-email').textContent=user.email||'';$('user-avatar').textContent=initials(n);$('menu-full-name').textContent=n;$('menu-full-email').textContent=user.email||'';$('menu-avatar').textContent=initials(n);$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};}
function show(msg,kind=''){const e=$('message');e.textContent=msg;e.className='message '+kind;}
function formMsg(msg,kind='error'){const e=$('form-message');e.textContent=msg;e.className='message '+kind;}
function openModal(row){editingId=row?.id||null;$('modal-title').textContent=editingId?'Editar conta':'Nova conta';$('account-name').value=row?.name||'';$('account-type').value=row?.account_type||'corrente';$('account-currency').value=row?.currency||'BRL — Real brasileiro';$('opening-balance').value=row?.opening_balance??'';formMsg('','');$('modal-backdrop').classList.remove('hidden');setTimeout(()=>$('account-name').focus(),50)}
function closeModal(){$('modal-backdrop').classList.add('hidden');editingId=null}
async function loadAccounts(){const {data,error}=await db().from('accounts').select('id,name,account_type,currency,opening_balance,created_at').eq('workspace_id',workspace.id).order('created_at',{ascending:true});if(error)throw error;const body=$('accounts-body');body.innerHTML='';$('empty').classList.toggle('hidden',!!data?.length);(data||[]).forEach(row=>{const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(row.name)}</strong></td><td>${esc(row.account_type)}</td><td>${esc(row.currency)}</td><td>${brl(row.opening_balance,row.currency)}</td><td><div class="actions"><button class="action" data-edit="${row.id}">Editar</button><button class="action danger" data-delete="${row.id}">Excluir</button></div></td>`;body.appendChild(tr)});body.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal((data||[]).find(x=>x.id===b.dataset.edit)));body.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeAccount(b.dataset.delete));}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function removeAccount(id){if(!confirm('Excluir esta conta? Esta ação não pode ser desfeita.'))return;show('Excluindo…');const {error}=await db().from('accounts').delete().eq('id',id).eq('workspace_id',workspace.id);if(error){show(error.message,'error');return}show('Conta excluída.','ok');await loadAccounts();}
$('new-account').onclick=()=>openModal();$('cancel-account').onclick=closeModal;$('modal-backdrop').onclick=e=>{if(e.target.id==='modal-backdrop')closeModal()};
$('save-account').onclick=async()=>{const button=$('save-account');button.disabled=true;formMsg('Salvando…','');try{const name=$('account-name').value.trim(),type=$('account-type').value,currency=$('account-currency').value,balance=Number($('opening-balance').value);if(!name)throw Error('Informe o nome da conta.');if(!Number.isFinite(balance)||balance<0)throw Error('Informe um saldo inicial válido.');const payload={name,account_type:type,currency,opening_balance:balance};let result;if(editingId)result=await db().from('accounts').update(payload).eq('id',editingId).eq('workspace_id',workspace.id);else result=await db().from('accounts').insert({...payload,workspace_id:workspace.id});if(result.error)throw result.error;closeModal();show(editingId?'Conta atualizada com sucesso.':'Conta cadastrada com sucesso.','ok');await loadAccounts();}catch(e){console.error(e);formMsg(e.message||'Não foi possível salvar a conta.');}finally{button.disabled=false}};
async function init(){const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const {data,error}=await db().from('user_workspaces').select('id,display_name,setup_completed').eq('user_id',s.user.id).maybeSingle();if(error)throw error;if(!data||!data.setup_completed){location.replace('workspace.html');return}workspace=data;header(s.user);await loadAccounts();}
init().catch(e=>{console.error(e);show('Não foi possível carregar suas contas.','error')});
})();