/* KORbuild Finances — New Account V1.1 */
(() => {
'use strict';
const $=id=>document.getElementById(id); const db=()=>KORbuildAuth.client.schema('finances'); let workspace=null;
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
function header(user){const n=workspace?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'André';$('user-name').textContent=n;$('user-email').textContent=user.email||'';$('user-avatar').textContent=initials(n);$('menu-full-name').textContent=n;$('menu-full-email').textContent=user.email||'';$('menu-avatar').textContent=initials(n);$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};}
function msg(text,kind='error'){const e=$('form-message');e.textContent=text;e.className='message '+kind;}
async function init(){const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const {data,error}=await db().from('user_workspaces').select('id,display_name,primary_currency,setup_completed').eq('user_id',s.user.id).maybeSingle();if(error)throw error;if(!data||!data.setup_completed){location.replace('workspace.html');return}workspace=data;if(data.primary_currency){const code=String(data.primary_currency).split(/\s+—\s+/)[0].trim().toUpperCase();if([...$('account-currency').options].some(o=>o.value===code))$('account-currency').value=code;}header(s.user);}
$('account-form').onsubmit=async e=>{e.preventDefault();const button=$('save-account');button.disabled=true;msg('Salvando…','');try{const name=$('account-name').value.trim(),account_type=$('account-type').value,currency=$('account-currency').value,opening_balance=Number($('opening-balance').value);if(!name)throw Error('Informe o nome da conta.');if(!Number.isFinite(opening_balance)||opening_balance<0)throw Error('Informe um saldo inicial válido.');const {error}=await db().from('accounts').insert({workspace_id:workspace.id,name,account_type,currency,opening_balance});if(error)throw error;location.replace('accounts.html?created=1');}catch(e){console.error(e);msg(e.message||'Não foi possível salvar a conta.');button.disabled=false;}};
init().catch(e=>{console.error(e);msg('Não foi possível carregar o formulário.');});
})();
