const STORAGE_KEY='korbuild-finances-wizard-v2';
const wizardState=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');
let step=Number(wizardState.step)||1;
let currentUser=null;
let saveTimer=null;
const $=id=>document.getElementById(id);
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
function saveLocal(){wizardState.step=step;localStorage.setItem(STORAGE_KEY,JSON.stringify(wizardState));}
function collectWizard(){const values={name:'wName',country:'wCountry',currency:'wCurrency',account:'wAccount',accountType:'wAccountType',accountCurrency:'wAccountCurrency',balance:'wBalance',incomeDesc:'wIncomeDesc',incomeCategory:'wIncomeCategory',income:'wIncome',frequency:'wFrequency',incomeDay:'wIncomeDay',goalName:'wGoalName',goalTarget:'wGoalTarget',goalYears:'wGoalYears',startDate:'wStartDate',initial:'wInitial'};Object.entries(values).forEach(([key,id])=>{const el=$(id);if(el)wizardState[key]=el.type==='number'?(Number(el.value)||0):el.value;});saveLocal();}
function draftData(){const data={...wizardState};delete data.step;return data;}
async function persistDraft(){if(!currentUser)return;collectWizard();clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{const {error}=await KORbuildAuth.client.schema('finances').from('setup_drafts').upsert({user_id:currentUser.id,current_step:step,data:draftData(),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;const status=document.querySelector('.save-status');if(status)status.textContent='Salvo com segurança.';}catch(error){console.error('Falha ao salvar configuração:',error);const status=document.querySelector('.save-status');if(status)status.textContent='Salvo neste dispositivo.';}},450);}
async function loadDraft(){if(!currentUser)return;const {data,error}=await KORbuildAuth.client.schema('finances').from('setup_drafts').select('current_step,data').eq('user_id',currentUser.id).maybeSingle();if(error){console.error('Falha ao carregar configuração:',error);return;}if(data?.data){Object.assign(wizardState,data.data);step=Number(data.current_step)||1;saveLocal();}}
async function getWorkspace(){const {data,error}=await KORbuildAuth.client.schema('finances').from('user_workspaces').select('id,setup_completed').eq('user_id',currentUser.id).maybeSingle();if(error)throw error;return data;}
async function ensureWorkspace(){const existing=await getWorkspace();if(existing?.setup_completed)return existing.id;const {data,error}=await KORbuildAuth.client.schema('finances').from('user_workspaces').upsert({user_id:currentUser.id,display_name:wizardState.name||null,country:wizardState.country||null,primary_currency:wizardState.currency||null,setup_completed:false,updated_at:new Date().toISOString()},{onConflict:'user_id'}).select('id').single();if(error)throw error;return data.id;}
async function completeSetup(){collectWizard();if(!currentUser)throw new Error('Sessão não encontrada.');const existing=await getWorkspace();if(existing?.setup_completed){localStorage.setItem('korbuild-finances-onboarding-complete','true');return {workspaceId:existing.id,alreadyComplete:true};}const workspaceId=await ensureWorkspace();const account={workspace_id:workspaceId,name:wizardState.account,account_type:wizardState.accountType,currency:wizardState.accountCurrency||wizardState.currency,opening_balance:Number(wizardState.balance||0)};const income={workspace_id:workspaceId,description:wizardState.incomeDesc,category:wizardState.incomeCategory,amount:Number(wizardState.income||0),currency:wizardState.currency,frequency:wizardState.frequency,receipt_day:wizardState.incomeDay?Number(wizardState.incomeDay):null};const goal={workspace_id:workspaceId,name:wizardState.goalName,target_amount:Number(wizardState.goalTarget||0),target_years:Number(wizardState.goalYears||0),start_date:wizardState.startDate,include_initial_wealth:Boolean(wizardState.includeInitial),initial_wealth:wizardState.includeInitial?Number(wizardState.initial||0):0};const {data:accountData,error:accountError}=await KORbuildAuth.client.schema('finances').from('accounts').insert(account).select('id').single();if(accountError)throw accountError;const {error:incomeError}=await KORbuildAuth.client.schema('finances').from('incomes').insert(income);if(incomeError)throw incomeError;const {data:goalData,error:goalError}=await KORbuildAuth.client.schema('finances').from('goals').insert(goal).select('id').single();if(goalError)throw goalError;const months=Math.max(1,Number(wizardState.goalYears||0)*12);const initial=wizardState.includeInitial?Number(wizardState.initial||0):0;const monthly=contribution(wizardState.goalTarget,initial,months);const {error:planError}=await KORbuildAuth.client.schema('finances').from('plans').insert({workspace_id:workspaceId,goal_id:goalData.id,projected_monthly_contribution:monthly,projected_monthly_rate:1.05});if(planError)throw planError;const {error:updateError}=await KORbuildAuth.client.schema('finances').from('user_workspaces').update({display_name:wizardState.name||null,country:wizardState.country||null,primary_currency:wizardState.currency||null,setup_completed:true,updated_at:new Date().toISOString()}).eq('id',workspaceId);if(updateError)throw updateError;await KORbuildAuth.client.schema('finances').from('setup_drafts').delete().eq('user_id',currentUser.id);localStorage.setItem('korbuild-finances-onboarding-complete','true');return {workspaceId,accountId:accountData.id,goalId:goalData.id};}
function fillWizard(){const values={name:'wName',country:'wCountry',currency:'wCurrency',account:'wAccount',accountType:'wAccountType',accountCurrency:'wAccountCurrency',balance:'wBalance',incomeDesc:'wIncomeDesc',incomeCategory:'wIncomeCategory',income:'wIncome',frequency:'wFrequency',incomeDay:'wIncomeDay',goalName:'wGoalName',goalTarget:'wGoalTarget',goalYears:'wGoalYears',startDate:'wStartDate',initial:'wInitial'};Object.entries(values).forEach(([key,id])=>{const el=$(id);if(el&&wizardState[key]!==undefined)el.value=wizardState[key];});const yes=document.querySelector('[data-choice="yes"]'),no=document.querySelector('[data-choice="no"]');if(wizardState.includeInitial){$('initialWealthWrap').classList.remove('hidden');yes.classList.add('selected');no.classList.remove('selected');}else{no.classList.add('selected');yes.classList.remove('selected');}}
function valid(){if(step===1)return !!wizardState.name&&!!wizardState.country&&!!wizardState.currency;if(step===2)return !!wizardState.account&&!!wizardState.accountType&&wizardState.balance>=0;if(step===3)return !!wizardState.incomeDesc&&!!wizardState.incomeCategory&&wizardState.income>0&&!!wizardState.frequency;if(step===4)return !!wizardState.goalName&&wizardState.goalTarget>0&&wizardState.goalYears>0&&!!wizardState.startDate;return true;}
function estimatedDate(){if(!wizardState.startDate||!wizardState.goalYears)return null;const d=new Date(wizardState.startDate+'T12:00:00');d.setFullYear(d.getFullYear()+Number(wizardState.goalYears));return d;}
function dateBR(d){return d?d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';}
function updateEstimatedDate(){const d=estimatedDate();$('estimatedDateValue').textContent=dateBR(d);$('estimatedDateText').textContent=d?`Com base em ${wizardState.goalYears} anos a partir de ${dateBR(new Date(wizardState.startDate+'T12:00:00'))}.`:'Informe os anos e a data inicial para calcular.';}
function contribution(target,initial,months,rate=1.05){const r=rate/100;if(months<=0)return 0;if(r===0)return Math.max(0,(target-initial)/months);const f=Math.pow(1+r,months);return Math.max(0,(target-initial*f)/((f-1)/r));}
function updatePlan(){collectWizard();$('summaryGoal').textContent=wizardState.goalName||'—';$('summaryTarget').textContent=brl(wizardState.goalTarget);$('summaryYears').textContent=wizardState.goalYears?`${wizardState.goalYears} anos`:'—';const d=estimatedDate();$('summaryDeadline').textContent=dateBR(d);const initial=wizardState.includeInitial?wizardState.initial:0;$('summaryInitial').textContent=brl(initial);const months=Math.max(1,Number(wizardState.goalYears||0)*12);$('summaryContribution').textContent=brl(contribution(wizardState.goalTarget,initial,months))+'/mês';}
function renderStep(){document.querySelectorAll('.step').forEach(x=>x.classList.toggle('step-active',Number(x.dataset.step)===step));document.querySelectorAll('.wizard-step').forEach(x=>{const n=Number(x.dataset.stepLink);x.classList.toggle('active',n===step);x.classList.toggle('done',n<step);});$('stepCounter').textContent=`${step} de 5`;$('stepProgress').style.width=(step*20)+'%';$('backBtn').disabled=step===1;$('nextBtn').textContent=step===5?'Começar minha jornada →':'Continuar →';$('nextBtn').disabled=!valid();if(step===4)updateEstimatedDate();if(step===5)updatePlan();saveLocal();}
function goNext(){collectWizard();if(!valid())return;if(step<5){step++;renderStep();persistDraft();}else finish();}
function goBack(){if(step>1){collectWizard();step--;renderStep();persistDraft();}}
async function finish(){const button=$('nextBtn');button.disabled=true;button.textContent='Finalizando…';try{const result=await completeSetup();alert(result.alreadyComplete?'Seu espaço financeiro já está configurado.':'Tudo pronto! Seu espaço financeiro foi configurado com sucesso.');window.location.replace('dashboard.html');}catch(error){console.error(error);alert(error.message||'Não foi possível concluir a configuração. Seus dados locais foram preservados.');button.disabled=false;button.textContent='Começar minha jornada →';}}
document.querySelectorAll('.step input,.step select').forEach(e=>e.addEventListener('input',()=>{collectWizard();renderStep();persistDraft();}));
document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{wizardState.includeInitial=b.dataset.choice==='yes';document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('initialWealthWrap').classList.toggle('hidden',!wizardState.includeInitial);collectWizard();renderStep();persistDraft();}));
document.querySelectorAll('.wizard-step').forEach(b=>b.addEventListener('click',()=>{const target=Number(b.dataset.stepLink);collectWizard();if(target<=step||valid()){step=target;renderStep();persistDraft();}}));
$('nextBtn').addEventListener('click',goNext);$('backBtn').addEventListener('click',goBack);
(async()=>{try{currentUser=await KORbuildAuth.session();if(!currentUser){window.location.replace('login.html');return;}const workspace=await getWorkspace();if(workspace?.setup_completed){window.location.replace('dashboard.html');return;}await loadDraft();fillWizard();renderStep();}catch(error){console.error(error);window.location.replace('login.html');}})();
