/* KORbuild Finances — Receitas V1 */
(() => {'use strict';
const $=id=>document.getElementById(id); const db=()=>KORbuildAuth.client.schema('finances'); let workspace=null;
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
const freq={weekly:'Semanal',biweekly:'Quinzenal',monthly:'Mensal',yearly:'Anual',eventual:'Eventual'};
function money(v,c){const code=String(c||'BRL').split(' ')[0];try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:code}).format(Number(v)||0)}catch{return `${Number(v||0).toFixed(2)} ${code}`}}
function monthly(i){const a=Number(i.amount)||0;return {weekly:a*52/12,biweekly:a*26/12,monthly:a,yearly:a/12,eventual:0}[i.frequency]||0}
function header(user){const n=workspace?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'André';$('user-name').textContent=n;$('user-email').textContent=user.email||'';$('user-avatar').textContent=initials(n);$('menu-full-name').textContent=n;$('menu-full-email').textContent=user.email||'';$('menu-avatar').textContent=initials(n);$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};}
async function init(){const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const {data,error}=await db().from('user_workspaces').select('id,display_name,setup_completed').eq('user_id',s.user.id).maybeSingle();if(error)throw error;if(!data?.setup_completed){location.replace('workspace.html');return}workspace=data;header(s.user);const r=await db().from('incomes').select('id,description,category,amount,currency,frequency,receipt_day').eq('workspace_id',workspace.id).order('created_at',{ascending:false});if(r.error)throw r.error;const rows=r.data||[];const list=$('income-list');list.innerHTML=rows.map(i=>`<tr><td><strong>${esc(i.description)}</strong></td><td>${esc(i.category)}</td><td>${money(i.amount,i.currency)}</td><td>${freq[i.frequency]||esc(i.frequency)}</td><td>${i.receipt_day?i.receipt_day:'—'}</td><td>${esc(i.currency)}</td><td><a class="edit-link" href="income-edit.html?id=${encodeURIComponent(i.id)}">Editar</a></td></tr>`).join('');$('income-count').textContent=rows.length;$('currency-count').textContent=new Set(rows.map(x=>x.currency)).size;const currencies=[...new Set(rows.map(x=>x.currency))];if(currencies.length===1){$('monthly-total').textContent=money(rows.reduce((s,i)=>s+monthly(i),0),currencies[0])}else if(currencies.length>1){$('monthly-total').textContent='Múltiplas moedas'}else{$('monthly-total').textContent=money(0,workspace.primary_currency||'BRL')}if(!rows.length)$('empty-state').classList.remove('hidden');}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
init().catch(e=>{console.error(e);$('table-status').textContent='Não foi possível carregar as receitas.'});
})();