/* KORbuild Finances — New Revenue V1 */
(() => {'use strict';
const $=id=>document.getElementById(id); const db=()=>KORbuildAuth.client.schema('finances'); let workspace=null;
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
function header(user){const n=workspace?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'André';$('user-name').textContent=n;$('user-email').textContent=user.email||'';$('user-avatar').textContent=initials(n);$('menu-full-name').textContent=n;$('menu-full-email').textContent=user.email||'';$('menu-avatar').textContent=initials(n);$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};}
function msg(t,k='error'){const e=$('form-message');e.textContent=t;e.className='message '+k}
function dayState(){const f=$('frequency').value;const show=['monthly','yearly'].includes(f);$('receipt-day-wrap').style.opacity=show?'1':'.55';$('receipt-day').disabled=!show}
async function init(){const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const {data,error}=await db().from('user_workspaces').select('id,display_name,primary_currency,setup_completed').eq('user_id',s.user.id).maybeSingle();if(error)throw error;if(!data?.setup_completed){location.replace('workspace.html');return}workspace=data;if(data.primary_currency&&[...$('currency').options].some(o=>o.text===data.primary_currency))$('currency').value=data.primary_currency;header(s.user);$('frequency').addEventListener('change',dayState);dayState()}
$('income-form').onsubmit=async e=>{e.preventDefault();const b=$('save-income');b.disabled=true;msg('Salvando…','');try{const description=$('description').value.trim(),category=$('category').value.trim(),amount=Number($('amount').value),currency=$('currency').value,frequency=$('frequency').value;const day=Number($('receipt-day').value);if(!description)throw Error('Informe a descrição.');if(!category)throw Error('Informe a categoria.');if(!Number.isFinite(amount)||amount<=0)throw Error('Informe um valor válido.');if(['monthly','yearly'].includes(frequency)&&$('receipt-day').value&&(!Number.isInteger(day)||day<1||day>31))throw Error('Informe um dia entre 1 e 31.');const {error}=await db().from('incomes').insert({workspace_id:workspace.id,description,category,amount,currency,frequency,receipt_day:['monthly','yearly'].includes(frequency)&&$('receipt-day').value?day:null});if(error)throw error;location.replace('incomes.html?created=1')}catch(e){console.error(e);msg(e.message||'Não foi possível salvar a receita.');b.disabled=false}};
init().catch(e=>{console.error(e);msg('Não foi possível carregar o formulário.')});
})();