/* KORbuild Finances — Edit Revenue V1 */
(() => {'use strict';
const $=id=>document.getElementById(id); const db=()=>KORbuildAuth.client.schema('finances'); let workspace=null,incomeId=new URLSearchParams(location.search).get('id');
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
function header(user){const n=workspace?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'André';$('user-name').textContent=n;$('user-email').textContent=user.email||'';$('user-avatar').textContent=initials(n);$('menu-full-name').textContent=n;$('menu-full-email').textContent=user.email||'';$('menu-avatar').textContent=initials(n);$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};}
function msg(t,k='error'){const e=$('form-message');e.textContent=t;e.className='message '+k}
function dayState(){const f=$('frequency').value;const show=['monthly','yearly'].includes(f);$('receipt-day-wrap').style.opacity=show?'1':'.55';$('receipt-day').disabled=!show}
async function init(){if(!incomeId)throw Error('Receita não informada.');const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const w=await db().from('user_workspaces').select('id,display_name,setup_completed').eq('user_id',s.user.id).maybeSingle();if(w.error)throw w.error;if(!w.data?.setup_completed){location.replace('workspace.html');return}workspace=w.data;header(s.user);const r=await db().from('incomes').select('id,description,category,amount,currency,frequency,receipt_day').eq('id',incomeId).eq('workspace_id',workspace.id).maybeSingle();if(r.error)throw r.error;if(!r.data)throw Error('Receita não encontrada.');const i=r.data;$('description').value=i.description;$('category').value=i.category;$('amount').value=i.amount;$('currency').value=i.currency;$('frequency').value=i.frequency;$('receipt-day').value=i.receipt_day||'';$('frequency').addEventListener('change',dayState);dayState()}
$('income-form').onsubmit=async e=>{e.preventDefault();const b=$('save-income');b.disabled=true;msg('Salvando…','');try{const description=$('description').value.trim(),category=$('category').value.trim(),amount=Number($('amount').value),currency=$('currency').value,frequency=$('frequency').value,day=Number($('receipt-day').value);if(!description)throw Error('Informe a descrição.');if(!category)throw Error('Informe a categoria.');if(!Number.isFinite(amount)||amount<=0)throw Error('Informe um valor válido.');if(['monthly','yearly'].includes(frequency)&&$('receipt-day').value&&(!Number.isInteger(day)||day<1||day>31))throw Error('Informe um dia entre 1 e 31.');const {error}=await db().from('incomes').update({description,category,amount,currency,frequency,receipt_day:['monthly','yearly'].includes(frequency)&&$('receipt-day').value?day:null}).eq('id',incomeId).eq('workspace_id',workspace.id);if(error)throw error;location.replace('incomes.html?updated=1')}catch(e){console.error(e);msg(e.message||'Não foi possível salvar.');b.disabled=false}};
$('delete-income').onclick=async()=>{if(!confirm('Excluir esta receita? Esta ação não pode ser desfeita.'))return;const b=$('delete-income');b.disabled=true;msg('Excluindo…','');try{const {error}=await db().from('incomes').delete().eq('id',incomeId).eq('workspace_id',workspace.id);if(error)throw error;location.replace('incomes.html?deleted=1')}catch(e){console.error(e);msg(e.message||'Não foi possível excluir.');b.disabled=false}};
init().catch(e=>{console.error(e);msg(e.message||'Não foi possível carregar a receita.')});
})();