/* KORbuild Finances — Investments V4 */
(()=>{'use strict';
const $=id=>document.getElementById(id),db=()=>KORbuildAuth.client.schema('finances');
let workspace=null,rows=[],types=[],transactions=[];
const currencyCode=c=>String(c||'BRL').split(' ')[0];
const money=(v,c)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:currencyCode(c),maximumFractionDigits:2});
const num=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:8});
const pct=v=>Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
const param=t=>{try{return typeof t?.parameters==='string'?JSON.parse(t.parameters||'{}'):(t?.parameters||{})}catch{return {}}};
function header(u){const n=workspace.display_name||u.user_metadata?.full_name||u.email?.split('@')[0]||'André';['user-name','menu-full-name'].forEach(id=>$(id).textContent=n);['user-email','menu-full-email'].forEach(id=>$(id).textContent=u.email||'');['user-avatar','menu-avatar'].forEach(id=>$(id).textContent=initials(n));$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};}
function msg(t,k=''){const e=$('message');e.textContent=t;e.className='message '+k}function fmsg(t,k='error'){const e=$('form-message');e.textContent=t;e.className='message '+k}
async function loadTypes(){const r=await db().from('investment_types').select('id,name,description,is_system,parameters').or(`workspace_id.is.null,workspace_id.eq.${workspace.id}`).order('is_system',{ascending:false}).order('name',{ascending:true});if(r.error)throw r.error;types=r.data||[];}
async function loadData(){const [ir,tr]=await Promise.all([db().from('investments').select('id,investment_type_id,name,symbol,currency').eq('workspace_id',workspace.id).order('name',{ascending:true}),db().from('investment_transactions').select('id,investment_id,transaction_type,transaction_date,quantity,unit_price,amount,currency,description').eq('workspace_id',workspace.id).order('transaction_date',{ascending:true}).order('created_at',{ascending:true})]);if(ir.error)throw ir.error;if(tr.error)throw tr.error;rows=ir.data||[];transactions=tr.data||[];render();}
function calcPosition(i){const ts=transactions.filter(t=>t.investment_id===i.id);let qty=0,cost=0,income=0,fees=0,withdrawals=0;for(const t of ts){const a=Number(t.amount||0),q=Number(t.quantity||0);if(t.transaction_type==='contribution'){cost+=a;qty+=q}else if(t.transaction_type==='withdrawal'){withdrawals+=a;qty=Math.max(0,qty-q)}else if(t.transaction_type==='income'||t.transaction_type==='dividend'){income+=a}else if(t.transaction_type==='fee'){fees+=a}else if(t.transaction_type==='adjustment'){if(q)qty+=q;cost+=a}}const invested=Math.max(0,cost-withdrawals);const p=param(types.find(t=>t.id===i.investment_type_id));const hasMarket=Boolean(p.uses_market_price||p.valuation_method==='quantity_price'||p.position_method==='quantity_price');const hasQty=Boolean(p.has_quantity||p.uses_quantity||hasMarket);const currentFromStored=Number(i.current_value||0);const storedPrice=Number(i.current_price||0);let current=currentFromStored;if(hasMarket&&qty>0&&storedPrice>0)current=qty*storedPrice;else if(!hasMarket&&currentFromStored>0)current=currentFromStored;const avg=qty>0?cost/qty:null;const result=current-invested+income-fees;return {qty,cost,invested,income,fees,current,avg,result,ret:invested?result/invested*100:0,hasQty,hasMarket};}
function render(){const body=$('investment-body');body.innerHTML='';let totalInvested=0,totalCurrent=0,totalResult=0;rows.forEach(i=>{const t=types.find(x=>x.id===i.investment_type_id),p=calcPosition(i);totalInvested+=p.invested;totalCurrent+=p.current;totalResult+=p.result;const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(i.name)}</strong>${i.symbol?` <span style="color:var(--muted)">${esc(i.symbol)}</span>`:''}</td><td><span class="badge">${esc(t?.name||'Não definido')}</span></td><td class="num">${p.hasQty?num(p.qty):'—'}</td><td class="num">${p.avg===null?'—':money(p.avg,i.currency)}</td><td class="num">${money(p.current,i.currency)}</td><td class="num ${p.result>=0?'gain':'loss'}">${money(p.result,i.currency)}</td><td class="num ${p.ret>=0?'gain':'loss'}">${pct(p.ret)}</td>`;body.appendChild(tr)});$('empty').classList.toggle('hidden',!!rows.length);const cur=rows[0]?.currency||workspace.primary_currency||'BRL';$('total-invested').textContent=money(totalInvested,cur);$('total-current').textContent=money(totalCurrent,cur);$('total-result').textContent=money(totalResult,cur);$('total-result').className=totalResult>=0?'gain':'loss';$('total-result-pct').textContent=pct(totalInvested?totalResult/totalInvested*100:0);}
function openModal(){fmsg('','');$('investment-type').innerHTML='<option value="">Selecione...</option>'+types.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');$('investment-name').value='';$('investment-symbol').value='';$('investment-currency').value=workspace.primary_currency||'BRL — Real brasileiro';$('modal-backdrop').classList.remove('hidden');setTimeout(()=>$('investment-name').focus(),50)}
function closeModal(){$('modal-backdrop').classList.add('hidden')}
$('new-investment').onclick=openModal;$('cancel-investment').onclick=closeModal;$('modal-backdrop').onclick=e=>{if(e.target.id==='modal-backdrop')closeModal()};$('save-investment').onclick=async()=>{const b=$('save-investment');b.disabled=true;fmsg('','');try{const typeId=$('investment-type').value,name=$('investment-name').value.trim(),symbol=$('investment-symbol').value.trim().toUpperCase(),currency=$('investment-currency').value;if(!typeId)throw Error('Selecione o tipo de investimento.');if(!name)throw Error('Informe o nome do investimento.');const r=await db().from('investments').insert({workspace_id:workspace.id,investment_type_id:typeId,name,symbol:symbol||null,currency,invested_amount:0,current_value:0,quantity:null,avg_price:null,current_price:null});if(r.error)throw r.error;closeModal();msg('Investimento criado. Agora registre os movimentos em Lançamentos.','ok');await loadData()}catch(e){console.error(e);fmsg(e.message||'Não foi possível criar o investimento.')}finally{b.disabled=false}};
async function init(){const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const r=await db().from('user_workspaces').select('id,display_name,setup_completed,primary_currency').eq('user_id',s.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data||!r.data.setup_completed){location.replace('workspace.html');return}workspace=r.data;header(s.user);await loadTypes();await loadData()}init().catch(e=>{console.error(e);msg('Não foi possível carregar seus investimentos.','error')});
})();