/* KORbuild Finances — New Investment V1 */
(()=>{'use strict';
const $=id=>document.getElementById(id),db=()=>KORbuildAuth.client.schema('finances');let workspace=null,types=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
const param=t=>{try{return typeof t?.parameters==='string'?JSON.parse(t.parameters||'{}'):(t?.parameters||{})}catch{return {}}};
function header(u){const n=workspace.display_name||u.user_metadata?.full_name||u.email?.split('@')[0]||'André';['user-name','menu-full-name'].forEach(id=>$(id).textContent=n);['user-email','menu-full-email'].forEach(id=>$(id).textContent=u.email||'');['user-avatar','menu-avatar'].forEach(id=>$(id).textContent=initials(n));$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')}}
function msg(t,k='error'){const e=$('form-message');e.textContent=t;e.className='message '+k}
function help(t){const p=param(t),e=$('type-help');if(!t){e.textContent='Selecione o tipo para visualizar como a posição será tratada.';return}if(p.valuation_method==='quantity_price'||p.position_method==='quantity_price'||p.uses_market_price)e.textContent='Este tipo trabalha com quantidade e preço de mercado. A posição será calculada a partir dos lançamentos e da cotação disponível.';else if(p.valuation_method==='accumulated_balance')e.textContent='Este tipo trabalha com saldo acumulado. O valor da posição será tratado como saldo patrimonial do investimento.';else e.textContent='Este tipo possui regras próprias de valorização. Os detalhes serão aplicados conforme a parametrização cadastrada.'}
async function loadTypes(){const r=await db().from('investment_types').select('id,name,description,is_system,parameters').or(`workspace_id.is.null,workspace_id.eq.${workspace.id}`).order('is_system',{ascending:false}).order('name',{ascending:true});if(r.error)throw r.error;types=r.data||[];$('investment-type').innerHTML='<option value="">Selecione...</option>'+types.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');$('investment-currency').value=workspace.primary_currency||'BRL — Real brasileiro';$('investment-type').onchange=()=>help(types.find(t=>t.id===$('investment-type').value))}
$('save-investment').onclick=async()=>{const b=$('save-investment');b.disabled=true;msg('');try{const typeId=$('investment-type').value,name=$('investment-name').value.trim(),symbol=$('investment-symbol').value.trim().toUpperCase(),currency=$('investment-currency').value;if(!typeId)throw Error('Selecione o tipo de investimento.');if(!name)throw Error('Informe o nome do investimento.');const r=await db().from('investments').insert({workspace_id:workspace.id,investment_type_id:typeId,name,symbol:symbol||null,currency,invested_amount:0,current_value:0,quantity:null,avg_price:null,current_price:null});if(r.error)throw r.error;location.replace('investments.html?created=1')}catch(e){console.error(e);msg(e.message||'Não foi possível criar o investimento.')}finally{b.disabled=false}};
async function init(){const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const r=await db().from('user_workspaces').select('id,display_name,setup_completed,primary_currency').eq('user_id',s.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data||!r.data.setup_completed){location.replace('workspace.html');return}workspace=r.data;header(s.user);await loadTypes()}init().catch(e=>{console.error(e);msg('Não foi possível carregar os tipos de investimento.')});
})();