/* KORbuild Finances — Investments V6 */
(()=>{'use strict';
const $=id=>document.getElementById(id),db=()=>KORbuildAuth.client.schema('finances');let workspace=null,rows=[],types=[];
const currencyCode=c=>String(c||'BRL').split(' ')[0];
const money=(v,c)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:currencyCode(c),maximumFractionDigits:2});
const num=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:8});
const pct=v=>Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
function header(u){const n=workspace.display_name||u.user_metadata?.full_name||u.email?.split('@')[0]||'André';['user-name','menu-full-name'].forEach(id=>$(id).textContent=n);['user-email','menu-full-email'].forEach(id=>$(id).textContent=u.email||'');['user-avatar','menu-avatar'].forEach(id=>$(id).textContent=initials(n));$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')}}
function msg(t,k=''){const e=$('message');e.textContent=t;e.className='message '+k}
async function loadTypes(){const r=await db().from('investment_types').select('id,name,description,is_system,parameters').or(`workspace_id.is.null,workspace_id.eq.${workspace.id}`).order('is_system',{ascending:false}).order('name',{ascending:true});if(r.error)throw r.error;types=r.data||[]}
async function loadData(){const r=await db().from('investment_positions').select('investment_id,workspace_id,investment_type_id,name,symbol,currency,quantity,cost_basis,contributions,withdrawals,income,fees,realized_gain,avg_price,current_price,position_value,valuation_status,result,return_pct,uses_market_price').eq('workspace_id',workspace.id).order('name',{ascending:true});if(r.error)throw r.error;rows=r.data||[];render()}
function positionLabel(p,c){if(p.valuation_status==='awaiting_price')return '<span style="color:var(--muted)">Aguardando cotação</span>';return money(p.position_value,c)}
function render(){const body=$('investment-body');body.innerHTML='';let totalInvested=0,totalCurrent=0,totalResult=0;const currencies=new Set(rows.map(r=>currencyCode(r.currency)));let currentCount=0;rows.forEach(i=>{const t=types.find(x=>x.id===i.investment_type_id);const hasQty=Number(i.quantity||0)>0||i.uses_market_price;const result=Number(i.result);if(i.position_value!==null){totalCurrent+=Number(i.position_value);currentCount++}totalInvested+=Number(i.contributions||0)-Number(i.withdrawals||0);if(Number.isFinite(result))totalResult+=result;const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(i.name)}</strong>${i.symbol?` <span style="color:var(--muted)">${esc(i.symbol)}</span>`:''}</td><td><span class="badge">${esc(t?.name||'Não definido')}</span></td><td class="num">${hasQty?num(i.quantity):'—'}</td><td class="num">${i.avg_price===null?'—':money(i.avg_price,i.currency)}</td><td class="num">${positionLabel(i,i.currency)}</td><td class="num ${Number.isFinite(result)?(result>=0?'gain':'loss'):''}">${Number.isFinite(result)?money(result,i.currency):'—'}</td><td class="num ${i.return_pct===null?'':(Number(i.return_pct)>=0?'gain':'loss')}">${i.return_pct===null?'—':pct(i.return_pct)}</td>`;body.appendChild(tr)});$('empty').classList.toggle('hidden',!!rows.length);const singleCurrency=currencies.size<=1;const cur=rows[0]?.currency||workspace.primary_currency||'BRL';$('total-invested').textContent=singleCurrency?money(totalInvested,cur):'Múltiplas moedas';$('total-current').textContent=singleCurrency?(currentCount===rows.length?money(totalCurrent,cur):'Parcial'): 'Múltiplas moedas';$('total-result').textContent=singleCurrency?money(totalResult,cur):'Múltiplas moedas';$('total-result').className=singleCurrency?(totalResult>=0?'gain':'loss'):'';$('total-result-pct').textContent=singleCurrency&&totalInvested>0?pct(totalResult/totalInvested*100):'—';const q=new URLSearchParams(location.search);if(q.get('created')==='1')msg('Investimento criado. Agora registre os movimentos em Lançamentos.','ok')}
async function init(){const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const r=await db().from('user_workspaces').select('id,display_name,setup_completed,primary_currency').eq('user_id',s.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data||!r.data.setup_completed){location.replace('workspace.html');return}workspace=r.data;header(s.user);await loadTypes();await loadData()}init().catch(e=>{console.error(e);msg('Não foi possível carregar seus investimentos.','error')});
})();