/* KORbuild Finances — Investment Types V3 */
(()=>{'use strict';const $=id=>document.getElementById(id),db=()=>KORbuildAuth.client.schema('finances');let workspace=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const methods={units_price:'Quantidade × preço atual',accumulated_balance:'Saldo acumulado / rendimento',manual_value:'Valor informado / institucional'};
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
function header(u){const n=workspace.display_name||u.user_metadata?.full_name||u.email?.split('@')[0]||'André';['user-name','menu-full-name'].forEach(id=>$(id).textContent=n);['user-email','menu-full-email'].forEach(id=>$(id).textContent=u.email||'');['user-avatar','menu-avatar'].forEach(id=>$(id).textContent=initials(n));$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap').contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};}
function msg(t,k=''){const e=$('message');e.textContent=t;e.className='message '+k}
function particularities(p){const a=[];if(p.quantity_enabled)a.push('Quantidade/cotas');if(p.market_price_enabled)a.push('Preço de mercado');if(p.income_enabled)a.push('Rendimentos/proventos');if(p.maturity_enabled)a.push('Vencimento');return a.length?a.join(' · '):'Sem parâmetros adicionais'}
async function load(){const r=await db().from('investment_types').select('id,name,description,is_system,parameters,created_at').or(`workspace_id.is.null,workspace_id.eq.${workspace.id}`).order('is_system',{ascending:false}).order('name',{ascending:true});if(r.error)throw r.error;const body=$('types-body');body.innerHTML='';(r.data||[]).forEach(t=>{const p=t.parameters||{};const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(t.name)}</strong><div style="font-size:9px;color:var(--muted);margin-top:3px">${esc(t.description||'')}</div></td><td><span class="method">${esc(methods[p.position_method]||'Não parametrizado')}</span></td><td style="font-size:9px;color:var(--muted)">${esc(particularities(p))}</td><td><span class="badge ${t.is_system?'':'custom'}">${t.is_system?'Padrão do sistema':'Personalizado'}</span></td>`;body.appendChild(tr)});$('empty').classList.toggle('hidden',!!r.data?.length)}
async function init(){const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}const r=await db().from('user_workspaces').select('id,display_name,setup_completed').eq('user_id',s.user.id).maybeSingle();if(r.error)throw r.error;if(!r.data||!r.data.setup_completed){location.replace('workspace.html');return}workspace=r.data;header(s.user);await load();const p=new URLSearchParams(location.search);if(p.get('created')==='1')msg('Tipo de investimento cadastrado com sucesso.','ok')}
init().catch(e=>{console.error(e);msg('Não foi possível carregar os tipos de investimento.','error')});})();