/* KORbuild Finances — Planejamento V2.0 */
(()=>{'use strict';
const $=id=>document.getElementById(id),db=()=>KORbuildAuth.client.schema('finances');
const money=(v,c='BRL')=>{try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:String(c||'BRL').split(/\s+—\s+/)[0].trim().toUpperCase(),maximumFractionDigits:0}).format(Number(v)||0)}catch{return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}};
const code=v=>String(v||'').split(/\s+—\s+/)[0].trim().toUpperCase();
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
const monthBounds=d=>{const s=new Date(d.getFullYear(),d.getMonth(),1),e=new Date(d.getFullYear(),d.getMonth()+1,1);return[s.toISOString().slice(0,10),e.toISOString().slice(0,10)]};
const futureValue=(present,monthly,n,rate)=>{const r=rate/100;return !n?present:present*Math.pow(1+r,n)+monthly*(r?((Math.pow(1+r,n)-1)/r):n)};
const requiredMonthly=(present,target,n,rate)=>{if(target<=present||n<=0)return 0;const r=rate/100,futurePresent=present*Math.pow(1+r,n),gap=target-futurePresent;return r?Math.max(0,gap*r/(Math.pow(1+r,n)-1)):gap/n};
function header(u,name){set('user-name',name);set('user-email',u.email||'');set('user-avatar',initials(name));set('menu-full-name',name);set('menu-full-email',u.email||'');set('menu-avatar',initials(name));$('user-menu-btn')?.addEventListener('click',e=>{e.stopPropagation();$('user-menu')?.classList.toggle('hidden')});document.addEventListener('click',()=> $('user-menu')?.classList.add('hidden'));$('logout')?.addEventListener('click',async()=>{await KORbuildAuth.logout();location.replace('index.html')});$('language-toggle')?.addEventListener('click',()=>{localStorage.setItem('korbuild-language',(localStorage.getItem('korbuild-language')||'pt-BR')==='pt-BR'?'en-US':'pt-BR');location.reload()})}
function projectionChart(current,target,planned,real,months,moneyFn){const el=$('projection-chart');if(!el)return;const n=Math.min(Math.max(months,6),60),w=760,h=220,pL=54,pR=12,pT=15,pB=30,max=Math.max(target,current,planned,real,1),pointsFor=v=>Array.from({length:n+1},(_,i)=>{const t=i/n,val=v(i);return{x:pL+t*(w-pL-pR),y:pT+(max-val)/max*(h-pT-pB)}}),planPts=pointsFor(i=>futureValue(current,planned,i,0)),realPts=pointsFor(i=>futureValue(current,real,i,0)),path=pts=>pts.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' '),area=`M ${planPts[0].x} ${h-pB} L ${planPts.map(p=>`${p.x} ${p.y}`).join(' L ')} L ${planPts[planPts.length-1].x} ${h-pB} Z`,grid=[0,.5,1].map(t=>{const y=pT+t*(h-pT-pB),v=max*(1-t);return `<line x1="${pL}" y1="${y}" x2="${w-pR}" y2="${y}" class="p-grid"/><text x="${pL-8}" y="${y+3}" text-anchor="end">${moneyFn(v)}</text>`}).join('');el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Projeção do plano versus realidade">${grid}<line x1="${pL}" y1="${pT+(max-target)/max*(h-pT-pB)}" x2="${w-pR}" y2="${pT+(max-target)/max*(h-pT-pB)}" class="p-target"/><path d="${area}" class="p-plan-area"/><path d="${path(planPts)}" class="p-plan"/><path d="${path(realPts)}" class="p-real"/><circle cx="${planPts[n].x}" cy="${planPts[n].y}" r="4" fill="#15935d"/><circle cx="${realPts[n].x}" cy="${realPts[n].y}" r="4" fill="#2474e8"/><text x="${pL}" y="${h-8}">Hoje</text><text x="${w-pR}" y="${h-8}" text-anchor="end">Prazo</text></svg>`}
async function load(){
 const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}
 const {data:w,error:we}=await db().from('user_workspaces').select('id,display_name,primary_currency,setup_completed').eq('user_id',s.user.id).maybeSingle();if(we)throw we;if(!w?.setup_completed){location.replace('workspace.html');return}
 header(s.user,w.display_name||s.user.email?.split('@')[0]||'André');
 const now=new Date(),[start,end]=monthBounds(now),sixStart=new Date(now.getFullYear(),now.getMonth()-5,1).toISOString().slice(0,10),primary=code(w.primary_currency||'BRL');
 const [{data:goals,error:ge},{data:plans,error:pe},{data:accounts,error:ae},{data:positions,error:pose},{data:tx,error:te},{data:expenses,error:ee},{data:incomes,error:ie}]=await Promise.all([
  db().from('goals').select('id,name,target_amount,target_years,start_date,initial_wealth,include_initial_wealth,created_at').eq('workspace_id',w.id).order('created_at',{ascending:false}).limit(1),
  db().from('plans').select('id,goal_id,projected_monthly_contribution,projected_monthly_rate,created_at').eq('workspace_id',w.id).order('created_at',{ascending:false}).limit(1),
  db().from('accounts').select('opening_balance,currency').eq('workspace_id',w.id),
  db().from('investment_positions').select('position_value,currency').eq('workspace_id',w.id),
  db().from('investment_transactions').select('amount,currency,transaction_type,transaction_date').eq('workspace_id',w.id).gte('transaction_date',sixStart).lt('transaction_date',end),
  db().from('expenses').select('amount,currency,status,paid_date').eq('workspace_id',w.id).gte('paid_date',sixStart).lt('paid_date',end),
  db().from('incomes').select('amount,currency,status,receipt_date').eq('workspace_id',w.id).gte('receipt_date',sixStart).lt('receipt_date',end)
 ]);if(ge||pe||ae||pose||te||ee||ie)throw ge||pe||ae||pose||te||ee||ie;
 const goal=(goals||[])[0];
 if(!goal){$('no-plan')?.classList.remove('hidden');$('plan-content')?.classList.add('hidden');return}
 $('plan-content')?.classList.remove('hidden');
 const plan=(plans||[])[0],ar=accounts||[],pos=positions||[],itx=tx||[],ex=expenses||[],inc=incomes||[];
 const balance=ar.filter(a=>code(a.currency)===primary).reduce((s,a)=>s+Number(a.opening_balance||0),0),investedValue=pos.filter(p=>code(p.currency)===primary).reduce((s,p)=>s+Number(p.position_value||0),0),currentWealth=goal.include_initial_wealth?Number(goal.initial_wealth||0):balance+investedValue;
 const monthlyPlan=Number(plan?.projected_monthly_contribution||0),rate=Number(plan?.projected_monthly_rate||0),years=Number(goal.target_years||0),months=Math.max(0,Math.round(years*12)),target=Number(goal.target_amount||0);
 const income6=inc.filter(x=>x.status==='realized'&&code(x.currency)===primary).reduce((s,x)=>s+Number(x.amount||0),0),expense6=ex.filter(x=>x.status==='realized'&&code(x.currency)===primary).reduce((s,x)=>s+Number(x.amount||0),0),invest6=itx.filter(x=>['contribution','adjustment'].includes(x.transaction_type)&&code(x.currency)===primary).reduce((s,x)=>s+Number(x.amount||0),0);
 const capacity=Math.max(0,(income6-expense6)/6),realInvestment=Math.max(0,invest6/6),required=requiredMonthly(currentWealth,target,months,rate),projected=futureValue(currentWealth,monthlyPlan,months,rate),realProjected=futureValue(currentWealth,realInvestment,months,rate),remaining=Math.max(0,target-currentWealth),progress=target?Math.min(100,Math.max(0,currentWealth/target*100)):0;
 const incomeMonth=inc.filter(x=>x.status==='realized'&&x.receipt_date>=start&&x.receipt_date<end&&code(x.currency)===primary).reduce((s,x)=>s+Number(x.amount||0),0),expenseMonth=ex.filter(x=>x.status==='realized'&&x.paid_date>=start&&x.paid_date<end&&code(x.currency)===primary).reduce((s,x)=>s+Number(x.amount||0),0),investMonth=itx.filter(x=>['contribution','adjustment'].includes(x.transaction_type)&&x.transaction_date>=start&&x.transaction_date<end&&code(x.currency)===primary).reduce((s,x)=>s+Number(x.amount||0),0);
 const moneyFn=v=>money(v,primary),rateText=rate.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'% a.m.';
 set('goal-name',goal.name||'Meu sonho');set('goal-description',`Meta de ${moneyFn(target)} em ${years||0} anos.`);set('target',moneyFn(target,primary));set('current-wealth',moneyFn(currentWealth,primary));set('remaining',moneyFn(remaining,primary));set('progress',progress.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%');
 set('real-capacity',moneyFn(capacity));set('real-investment',moneyFn(realInvestment));set('monthly-plan',moneyFn(monthlyPlan));set('required-monthly',moneyFn(required));set('required-gap',(monthlyPlan>=required?'+ ':'− ')+moneyFn(Math.abs(monthlyPlan-required)));set('plan-rate',rateText);
 set('projected',moneyFn(projected));set('real-projected',moneyFn(realProjected));set('projected-gap',realProjected>=target?'Objetivo alcançado pelo ritmo real':'Faltariam '+moneyFn(Math.max(0,target-realProjected))+' no ritmo real');
 set('month-income',moneyFn(incomeMonth));set('month-expenses',moneyFn(expenseMonth));set('month-invested',moneyFn(investMonth));
 const bar=$('progress-bar');if(bar)bar.style.width=progress+'%';
 const status=$('plan-status'),onTrack=capacity>=required&&required>0;if(status){status.textContent=onTrack?'Você está no caminho':'Precisamos ajustar o ritmo';status.className='plan-status '+(onTrack?'on-track':'attention')}
 const badge=$('projection-badge'),planOnTrack=projected>=target;if(badge){badge.textContent=planOnTrack?'Plano alcança a meta':'Plano ainda não alcança a meta';badge.className='projection-badge '+(planOnTrack?'on-track':'attention')}
 set('reality-note',capacity>=required&&required>0?'Sua capacidade média dos últimos 6 meses está acima do ritmo necessário.':'Sua capacidade média dos últimos 6 meses ainda está abaixo do ritmo necessário para a meta.');
 set('next-title',capacity>=required?'Continue e acompanhe':'O plano precisa de atenção');set('next-text',capacity>=required?'Os dados atuais sustentam o ritmo necessário. O próximo fechamento patrimonial será importante para confirmar se essa trajetória continua.':'Há uma diferença entre sua capacidade média e o ritmo necessário. O sistema não muda sua meta: ele mostra o que precisa ser ajustado na realidade.');set('next-highlight',capacity>=required?`Margem atual: ${moneyFn(capacity-required)} por mês.`:`Ajuste necessário: ${moneyFn(required-capacity)} por mês.`);
 projectionChart(currentWealth,target,monthlyPlan,realInvestment,months,moneyFn);
}
load().catch(e=>{console.error(e);const st=$('status');if(st){st.textContent='Não foi possível carregar o planejamento.';st.classList.remove('hidden')}});
})();