/* KORbuild Finances — Planejamento V3.3 */
(()=>{'use strict';
const $=id=>document.getElementById(id),db=()=>KORbuildAuth.client.schema('finances');
const money=(v,c='BRL')=>{try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:String(c||'BRL').split(/\s+—\s+/)[0].trim().toUpperCase(),maximumFractionDigits:0}).format(Number(v)||0)}catch{return 'R$ '+Math.round(Number(v)||0).toLocaleString('pt-BR')}};
const code=v=>String(v||'').split(/\s+—\s+/)[0].trim().toUpperCase();
const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};
const initials=n=>String(n||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
const monthKey=d=>{if(!d)return '';const x=new Date(String(d).length===10?d+'T12:00:00':d);return Number.isNaN(x.getTime())?'':`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
const bounds=d=>[new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10),new Date(d.getFullYear(),d.getMonth()+1,1).toISOString().slice(0,10)];
const fv=(p,m,n,r)=>{const x=r/100;return !n?p:p*Math.pow(1+x,n)+m*(x?(Math.pow(1+x,n)-1)/x:n)};
const required=(p,t,n,r)=>{if(t<=p||n<=0)return 0;const x=r/100,fp=p*Math.pow(1+x,n),gap=t-fp;return x?Math.max(0,gap*x/(Math.pow(1+x,n)-1)):gap/n};
function header(u,name){set('user-name',name);set('user-email',u.email||'');set('user-avatar',initials(name));set('menu-full-name',name);set('menu-full-email',u.email||'');set('menu-avatar',initials(name));$('user-menu-btn')?.addEventListener('click',e=>{e.stopPropagation();$('user-menu')?.classList.toggle('hidden')});document.addEventListener('click',()=> $('user-menu')?.classList.add('hidden'));$('logout')?.addEventListener('click',async()=>{await KORbuildAuth.logout();location.replace('index.html')});$('language-toggle')?.addEventListener('click',()=>{localStorage.setItem('korbuild-language',(localStorage.getItem('korbuild-language')||'pt-BR')==='pt-BR'?'en-US':'pt-BR';location.reload()})}
function chart(current,target,planned,real,months,fmt){const el=$('projection-chart');if(!el)return;const n=Math.min(Math.max(months,6),60),w=760,h=220,l=54,r=12,t=15,b=30,vals=[];for(let i=0;i<=n;i++)vals.push(fv(current,planned,i,0),fv(current,real,i,0));const max=Math.max(target,current,...vals,1),pts=fn=>Array.from({length:n+1},(_,i)=>{const v=fn(i),x=l+i/n*(w-l-r),y=t+(max-v)/max*(h-t-b);return[x,y]}),pp=pts(i=>fv(current,planned,i,0)),rp=pts(i=>fv(current,real,i,0)),path=a=>a.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' '),gy=[0,.5,1].map(q=>{const y=t+q*(h-t-b),v=max*(1-q);return `<line x1="${l}" y1="${y}" x2="${w-r}" y2="${y}" class="p-grid"/><text x="${l-8}" y="${y+3}" text-anchor="end">${fmt(v)}</text>`}).join('');el.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Projeção do plano versus realidade">${gy}<line x1="${l}" y1="${t+(max-target)/max*(h-t-b)}" x2="${w-r}" y2="${t+(max-target)/max*(h-t-b)}" class="p-target"/><path d="${path(pp)}" class="p-plan"/><path d="${path(rp)}" class="p-real"/><text x="${l}" y="${h-8}">Hoje</text><text x="${w-r}" y="${h-8}" text-anchor="end">Prazo</text></svg>`}
function showError(e){console.error(e);const st=$('status');if(st){st.textContent='Erro ao carregar Planejamento: '+(e?.message||String(e));st.classList.remove('hidden')}$('plan-content')?.classList.remove('hidden')}
async function query(label,run,optional=false){const res=await run();if(res.error){if(optional){console.warn(label,res.error);return {data:[]}}throw new Error(label+': '+(res.error.message||JSON.stringify(res.error)))}return res.data||[]}
async function load(){
 const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return}
 const w=await query('workspace',()=>db().from('user_workspaces').select('id,display_name,primary_currency,setup_completed').eq('user_id',s.user.id).maybeSingle());
 if(!w?.setup_completed){location.replace('workspace.html');return} header(s.user,w.display_name||s.user.email?.split('@')[0]||'André');
 const goals=await query('objetivo',()=>db().from('goals').select('id,name,target_amount,target_years,start_date,initial_wealth,include_initial_wealth,created_at').eq('workspace_id',w.id).order('created_at',{ascending:false}).limit(1));
 const goal=goals[0];if(!goal){$('no-plan')?.classList.remove('hidden');$('plan-content')?.classList.add('hidden');return}$('plan-content')?.classList.remove('hidden');
 const now=new Date(),[start,end]=bounds(now),analysisStart=new Date(now.getFullYear(),now.getMonth()-11,1).toISOString().slice(0,10),primary=code(w.primary_currency||'BRL');
 const plans=await query('plano',()=>db().from('plans').select('id,goal_id,projected_monthly_contribution,projected_monthly_rate,created_at').eq('workspace_id',w.id).order('created_at',{ascending:false}).limit(1),true);
 const ar=await query('contas',()=>db().from('accounts').select('opening_balance,currency').eq('workspace_id',w.id),true);
 const pos=await query('posições',()=>db().from('investment_positions').select('position_value,currency').eq('workspace_id',w.id),true);
 const tx=await query('investimentos',()=>db().from('investment_transactions').select('amount,currency,transaction_type,transaction_date').eq('workspace_id',w.id).gte('transaction_date',analysisStart).lt('transaction_date',end),true);
 const ex=await query('despesas',()=>db().from('expenses').select('amount,currency,status,paid_date').eq('workspace_id',w.id).gte('paid_date',analysisStart).lt('paid_date',end),true);
 const inc=await query('receitas',()=>db().from('incomes').select('amount,currency,status,receipt_date').eq('workspace_id',w.id).gte('receipt_date',analysisStart).lt('receipt_date',end),true);
 const plan=plans[0],balance=ar.filter(a=>code(a.currency)===primary).reduce((s,a)=>s+Number(a.opening_balance||0),0),investedValue=pos.filter(p=>code(p.currency)===primary).reduce((s,p)=>s+Number(p.position_value||0),0),current=goal.include_initial_wealth?Number(goal.initial_wealth||0):balance+investedValue,target=Number(goal.target_amount||0),years=Number(goal.target_years||0),months=Math.max(0,Math.round(years*12)),monthly=Number(plan?.projected_monthly_contribution||0),rate=Number(plan?.projected_monthly_rate||0);
 const buckets=new Map(),add=(d,k,v)=>{const m=monthKey(d);if(!m)return;if(!buckets.has(m))buckets.set(m,{income:0,expense:0,investment:0});buckets.get(m)[k]+=Number(v||0)};
 inc.filter(x=>x.status==='realized'&&code(x.currency)===primary).forEach(x=>add(x.receipt_date,'income',x.amount));ex.filter(x=>x.status==='realized'&&code(x.currency)===primary).forEach(x=>add(x.paid_date,'expense',x.amount));tx.filter(x=>['contribution','adjustment'].includes(x.transaction_type)&&code(x.currency)===primary).forEach(x=>add(x.transaction_date,'investment',x.amount));
 const active=[...buckets.values()].filter(m=>m.income||m.expense||m.investment),n=active.length||1,sum=k=>active.reduce((s,m)=>s+Number(m[k]||0),0),capacity=(sum('income')-sum('expense'))/n,investAvg=sum('investment')/n,req=required(current,target,months,rate),projected=fv(current,monthly,months,rate),realProjected=fv(current,Math.max(0,investAvg),months,rate),remaining=Math.max(0,target-current),progress=target?Math.min(100,Math.max(0,current/target*100)):0,fmt=v=>money(v,primary);
 const thisIncome=inc.filter(x=>x.status==='realized'&&x.receipt_date>=start&&x.receipt_date<end&&code(x.currency)===primary).reduce((s,x)=>s+Number(x.amount||0),0),thisExpense=ex.filter(x=>x.status==='realized'&&x.paid_date>=start&&x.paid_date<end&&code(x.currency)===primary).reduce((s,x)=>s+Number(x.amount||0),0),thisInvest=tx.filter(x=>['contribution','adjustment'].includes(x.transaction_type)&&x.transaction_date>=start&&x.transaction_date<end&&code(x.currency)===primary).reduce((s,x)=>s+Number(x.amount||0),0);
 set('goal-name',goal.name||'Meu sonho');set('goal-description',`Meta de ${fmt(target)} em ${years} anos.`);set('target',fmt(target));set('current-wealth',fmt(current));set('remaining',fmt(remaining));set('progress',progress.toLocaleString('pt-BR',{maximumFractionDigits:1})+'%');set('real-capacity',fmt(capacity));set('real-investment',fmt(investAvg));set('monthly-plan',fmt(monthly));set('required-monthly',fmt(req));set('required-gap',(monthly>=req?'+ ':'− ')+fmt(Math.abs(monthly-req)));set('plan-rate',rate.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'% a.m.');set('projected',fmt(projected));set('real-projected',fmt(realProjected));set('projected-gap',realProjected>=target?'Objetivo alcançado pelo ritmo real':'Faltariam '+fmt(Math.max(0,target-realProjected)));set('month-income',fmt(thisIncome));set('month-expenses',fmt(thisExpense));set('month-invested',fmt(thisInvest));
 const badge=document.querySelector('.period-badge'),labels=document.querySelectorAll('.reality-grid .big-metric small');if(badge)badge.textContent=active.length===0?'Sem dados':active.length===1?'1 mês com dados':`${Math.min(active.length,12)} meses com dados`;if(labels[0])labels[0].textContent=active.length<=1?'Capacidade no mês':'Capacidade média de acumulação';if(labels[1])labels[1].textContent=active.length<=1?'Investimento no mês':'Investimento médio';set('reality-note',active.length===0?'Ainda não há movimentações registradas.':active.length===1?'A análise usa 1 mês de dados. Novos lançamentos atualizarão automaticamente a análise.':`A análise usa ${Math.min(active.length,12)} meses com dados dentro da janela móvel de até 12 meses.`);
 const bar=$('progress-bar');if(bar)bar.style.width=progress+'%';const onTrack=req>0&&capacity>=req,status=$('plan-status');if(status){status.textContent=onTrack?'Você está no caminho':'Precisamos ajustar o ritmo';status.className='plan-status '+(onTrack?'on-track':'attention')}const pb=$('projection-badge');if(pb){pb.textContent=projected>=target?'Plano alcança a meta':'Plano ainda não alcança a meta';pb.className='projection-badge '+(projected>=target?'on-track':'attention')}set('next-title',onTrack?'Continue e acompanhe':'O plano precisa de atenção');set('next-text',onTrack?'Os dados atuais sustentam o ritmo necessário.':'Há uma diferença entre sua capacidade média e o ritmo necessário.');set('next-highlight',onTrack?`Margem atual: ${fmt(capacity-req)} por mês.`:`Ajuste necessário: ${fmt(req-capacity)} por mês.`);chart(current,target,monthly,Math.max(0,investAvg),months,fmt);
}
load().catch(showError);
})();