/* KORbuild Finances — Settings V1.1 */
(() => {
'use strict';
const $=id=>document.getElementById(id); const db=()=>KORbuildAuth.client.schema('finances'); let workspace=null;
const initials=name=>String(name||'').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'A';
function header(user){const name=workspace?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'André';$('user-name').textContent=name;$('user-email').textContent=user.email||'';$('user-avatar').textContent=initials(name);$('menu-full-name').textContent=name;$('menu-full-email').textContent=user.email||'';$('menu-avatar').textContent=initials(name);}
async function init(){const session=await KORbuildAuth.session();if(!session?.user){location.replace('index.html');return}const {data,error}=await db().from('user_workspaces').select('id,display_name,country,primary_currency,setup_completed').eq('user_id',session.user.id).maybeSingle();if(error)throw error;if(!data||!data.setup_completed){location.replace('workspace.html');return}workspace=data;header(session.user);$('name').value=data.display_name||'';$('country').value=data.country||'';$('currency').value=data.primary_currency||'';}
$('cancel').onclick=()=>location.replace('dashboard.html');$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{const w=document.querySelector('.user-menu-wrap');if(w&&!w.contains(e.target))$('user-menu').classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};
$('save').onclick=async()=>{const msg=$('message'),btn=$('save');btn.disabled=true;msg.className='save-message';msg.textContent='Salvando…';try{const name=$('name').value.trim(),country=$('country').value,currency=$('currency').value;if(!name||!country||!currency)throw Error('Preencha nome, país e moeda principal.');const {error}=await db().from('user_workspaces').update({display_name:name,country,primary_currency:currency}).eq('id',workspace.id);if(error)throw error;workspace={...workspace,display_name:name,country,primary_currency:currency};header((await KORbuildAuth.session()).user);msg.className='save-message ok';msg.textContent='Alterações salvas com sucesso.'}catch(e){console.error(e);msg.className='save-message error';msg.textContent=e.message||'Não foi possível salvar as alterações.'}finally{btn.disabled=false}};
init().catch(e=>{console.error('Settings init failed',e);$('message').className='save-message error';$('message').textContent='Não foi possível carregar a configuração.'});
})();