/* KORbuild Finances — Transferências V1.1 */
(()=>{'use strict';const $=id=>document.getElementById(id);const db=()=>KORbuildAuth.client.schema('finances');let w,accounts=[];
const money=(v,c)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:(c||'BRL').split(' ')[0],maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=n=>String(n||'A').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
function header(user,name){$('user-name').textContent=name;$('user-email').textContent=user.email||'';$('user-avatar').textContent=initials(name);$('menu-full-name').textContent=name;$('menu-full-email').textContent=user.email||'';$('menu-avatar').textContent=initials(name);$('user-menu-btn').onclick=e=>{e.stopPropagation();$('user-menu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!document.querySelector('.user-menu-wrap')?.contains(e.target))$('user-menu')?.classList.add('hidden')});$('logout').onclick=async()=>{await KORbuildAuth.logout();location.replace('index.html')};}
async function init(){const s=await KORbuildAuth.session();if(!s?.user){location.replace('index.html');return;}const wr=await db().from('user_workspaces').select('id,display_name,setup_completed').eq('user_id',s.user.id).maybeSingle();if(wr.error)throw wr.error;if(!wr.data?.setup_completed){location.replace('workspace.html');return;}w=wr.data;header(s.user,w.display_name||s.user.email?.split('@')[0]||'Você');const [ar,tr]=await Promise.all([db().from('accounts').select('id,name,currency').eq('workspace_id',w.id).order('name'),db().from('transfers').select('id,source_account_id,destination_account_id,source_amount,destination_amount,source_currency,destination_currency,fx_rate,transfer_date,description').eq('workspace_id',w.id).order('transfer_date',{ascending:false}).order('created_at',{ascending:false})]);if(ar.error)throw ar.error;if(tr.error)throw tr.error;accounts=ar.data||[];const map=Object.fromEntries(accounts.map(a=>[a.id,a]));const rows=tr.data||[];$('transfer-count').textContent=rows.length;$('month-count').textContent=rows.filter(r=>String(r.transfer_date).slice(0,7)===new Date().toISOString().slice(0,7)).length;$('transfer-list').innerHTML=rows.length?rows.map(r=>{const s=map[r.source_account_id],d=map[r.destination_account_id];const fx=r.source_currency!==r.destination_currency?` · câmbio ${Number(r.fx_rate).toLocaleString('pt-BR',{maximumFractionDigits:6})}`:'';return `<div class="expense-row"><div class="expense-main"><strong>${esc(r.description||'Transferência entre contas')}</strong><small>${esc(s?.name||'Conta de origem')} → ${esc(d?.name||'Conta de destino')} · ${new Date(r.transfer_date+'T12:00:00').toLocaleDateString('pt-BR')}${fx}</small></div><div class="expense-amount">${money(r.source_amount,r.source_currency)}${r.source_currency!==r.destination_currency?` → ${money(r.destination_amount,r.destination_currency)}`:''}</div><div class="expense-actions-cell"><a class="mini-action" href="transfer-edit.html?id=${encodeURIComponent(r.id)}">Editar</a><button class="mini-action" data-delete="${r.id}">Excluir</button></div></div>`}).join(''):'<div class="empty-state">Nenhuma transferência registrada ainda.<br><a href="transfer-new.html">Registrar a primeira transferência</a></div>';$('transfer-list').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));}
async function remove(id){if(!confirm('Excluir esta transferência?'))return;const {error}=await db().from('transfers').delete().eq('id',id).eq('workspace_id',w.id);if(error){alert('Não foi possível excluir a transferência.');console.error(error);return;}location.reload();}
init().catch(e=>{console.error(e);$('transfer-list').innerHTML='<div class="empty-state">Não foi possível carregar as transferências.</div>';});})();
